title: Andrey Ivanov # your name (or website title) here
logo: "/images/Andrey Ivanov.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI Algorithm and Computer Vision Researcher 
 
  <a href="https://www.linkedin.com/in/andrey-ivanov1/">View My LinkedIn Profile</a>  
