title: Andrey Ivanov # your name (or website title) here
logo: "/images/portfolio_logo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI Algorithm and Computer Vision Team Tech Lead and Researcher with 15+ years of experience in the high-tech and security industries  
  <br><br>
  <a href="https://www.linkedin.com/in/andrey-ivanov1/">View My LinkedIn Profile</a>  
  
theme: jekyll-theme-minimal
